name: Publicar pacote no PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build e Upload para PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências de build
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Construir pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
